name: ultimate360s
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^2.22.0
  # Firebase Authentication
  firebase_auth: ^4.16.0
  # Firestore
  cloud_firestore: ^4.10.0
  
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/bg.png
    - lib/assets/bg1.png
    - lib/assets/amigos.png

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
